[versions]
kotlin = "2.1.20"
groovy = "3.0.15"
spock = "2.3-groovy-3.0"
protobuf = "3.21.12"
# Ladybug Patch 1 (2024.2.1.10)
testAndroidStudioVersion = "2024.2.1.10"
testAndroidSdkVersion = "7.3.0"

[libraries]
toolingApi = "org.gradle:gradle-tooling-api:8.14.3"

spock-core = { module = "org.spockframework:spock-core", version.ref = "spock" }
spock-junit4 = { module = "org.spockframework:spock-junit4", version.ref = "spock" }

groovy-core = { module = "org.codehaus.groovy:groovy", version.ref = "groovy" }
groovy-xml = { module = "org.codehaus.groovy:groovy-xml", version.ref = "groovy" }

typesafe-config = { module = "com.typesafe:config", version = "1.3.3" }
protobuf-java = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }
protobuf-protoc = { module = "com.google.protobuf:protoc", version.ref = "protobuf" }
gson = { module = "com.google.code.gson:gson", version = "2.10" }

[bundles]
testDependencies = ["spock-core", "spock-junit4", "groovy-core"]

[plugins]
protobuf = { id = "com.google.protobuf", version = "0.9.4" }
