[versions]
groovy = "3.0.15"
spock = "2.1-groovy-3.0"
# Iguana (2023.2.1.7) Canary 7
testAndroidStudioVersion = "2023.2.1.7"
testAndroidSdkVersion = "7.3.0"

[libraries]
commonIo = "commons-io:commons-io:2.11.0"
ideStarter = "com.jetbrains.intellij.tools:ide-starter-squashed:233.14475.28"
toolingApi = "org.gradle:gradle-tooling-api:7.2"

spock-core = { module = "org.spockframework:spock-core", version.ref = "spock" }
spock-junit4 = { module = "org.spockframework:spock-junit4", version.ref = "spock" }

groovy-core = { module = "org.codehaus.groovy:groovy", version.ref = "groovy" }
groovy-xml = { module = "org.codehaus.groovy:groovy-xml", version.ref = "groovy" }

[bundles]
testDependencies = ["spock-core", "spock-junit4", "groovy-core"]
